begin;

create table if not exists public.aspirasi_ramadhan (
  id bigint generated by default as identity primary key,
  submission_token uuid not null default gen_random_uuid(),
  created_at timestamptz not null default now(),
  form_version text not null default '1448h-v2',
  program_prioritas text[] not null,
  program_lainnya text,
  area_peningkatan text[] not null,
  peningkatan_lainnya text,
  program_dipertahankan text,
  program_dipertahankan_pilihan text[],
  program_dipertahankan_lainnya text,
  usulan_baru text,
  partisipasi text not null,
  saran_lain text,
  nama text,
  whatsapp text,
  source_channel text not null default 'website',
  status text not null default 'baru',
  catatan_internal text,
  reviewed_at timestamptz,
  reviewed_by uuid
);

alter table public.aspirasi_ramadhan drop constraint if exists aspirasi_ramadhan_submission_token_key;
alter table public.aspirasi_ramadhan add constraint aspirasi_ramadhan_submission_token_key unique (submission_token);

alter table public.aspirasi_ramadhan drop constraint if exists aspirasi_ramadhan_program_prioritas_check;
alter table public.aspirasi_ramadhan add constraint aspirasi_ramadhan_program_prioritas_check check (
  cardinality(program_prioritas) between 1 and 5
  and program_prioritas <@ array[
    'pra_ramadhan','tarawih_witir','kultum_kajian','tadarus','ifthar_tajil','pesantren_anak',
    'itikaf_10_malam','santunan_ziswaf','zakat_infaq_fidyah','santunan_yatim_dhuafa',
    'takbir_idul_fitri','halal_bihalal','lainnya'
  ]::text[]
);

alter table public.aspirasi_ramadhan drop constraint if exists aspirasi_ramadhan_program_lainnya_check;
alter table public.aspirasi_ramadhan add constraint aspirasi_ramadhan_program_lainnya_check check (
  char_length(coalesce(program_lainnya,'')) <= 200
  and (not ('lainnya' = any(program_prioritas)) or nullif(btrim(program_lainnya),'') is not null)
);

alter table public.aspirasi_ramadhan drop constraint if exists aspirasi_ramadhan_area_peningkatan_check;
alter table public.aspirasi_ramadhan add constraint aspirasi_ramadhan_area_peningkatan_check check (
  cardinality(area_peningkatan) between 1 and 3
  and area_peningkatan <@ array[
    'kenyamanan_ibadah','kualitas_kajian','anak_remaja','tajil_buka_puasa','kebersihan_fasilitas',
    'informasi_kegiatan','pengelolaan_ziswaf','kualitas_imam_khatib_tarawih','kualitas_mc_tarawih',
    'sepuluh_malam_terakhir','tidak_ada','lainnya'
  ]::text[]
  and (not ('tidak_ada' = any(area_peningkatan)) or cardinality(area_peningkatan) = 1)
);

alter table public.aspirasi_ramadhan drop constraint if exists aspirasi_ramadhan_peningkatan_lainnya_check;
alter table public.aspirasi_ramadhan add constraint aspirasi_ramadhan_peningkatan_lainnya_check check (
  char_length(coalesce(peningkatan_lainnya,'')) <= 200
  and (not ('lainnya' = any(area_peningkatan)) or nullif(btrim(peningkatan_lainnya),'') is not null)
);

alter table public.aspirasi_ramadhan drop constraint if exists aspirasi_ramadhan_program_dipertahankan_pilihan_check;
alter table public.aspirasi_ramadhan add constraint aspirasi_ramadhan_program_dipertahankan_pilihan_check check (
  program_dipertahankan_pilihan is null
  or (
    cardinality(program_dipertahankan_pilihan) between 1 and 5
    and program_dipertahankan_pilihan <@ array[
      'pra_ramadhan','tarawih_witir','kultum_kajian','tadarus','ifthar_tajil','pesantren_anak',
      'itikaf_10_malam','zakat_infaq_fidyah','santunan_yatim_dhuafa',
      'takbir_idul_fitri','halal_bihalal','lainnya'
    ]::text[]
  )
);

alter table public.aspirasi_ramadhan drop constraint if exists aspirasi_ramadhan_program_dipertahankan_lainnya_check;
alter table public.aspirasi_ramadhan add constraint aspirasi_ramadhan_program_dipertahankan_lainnya_check check (
  char_length(coalesce(program_dipertahankan_lainnya,'')) <= 200
  and (
    program_dipertahankan_pilihan is null
    or not ('lainnya' = any(program_dipertahankan_pilihan))
    or nullif(btrim(program_dipertahankan_lainnya),'') is not null
  )
);

alter table public.aspirasi_ramadhan drop constraint if exists aspirasi_ramadhan_partisipasi_check;
alter table public.aspirasi_ramadhan add constraint aspirasi_ramadhan_partisipasi_check check (
  partisipasi in ('relawan','donatur','relawan_dan_donatur','mungkin','belum')
);

alter table public.aspirasi_ramadhan drop constraint if exists aspirasi_ramadhan_status_check;
alter table public.aspirasi_ramadhan add constraint aspirasi_ramadhan_status_check check (
  status in ('baru','dibaca','ditindaklanjuti','selesai')
);

alter table public.aspirasi_ramadhan drop constraint if exists aspirasi_ramadhan_source_channel_check;
alter table public.aspirasi_ramadhan add constraint aspirasi_ramadhan_source_channel_check check (
  source_channel in ('website','standing_banner','pengumuman_lisan','input_admin')
);

alter table public.aspirasi_ramadhan drop constraint if exists aspirasi_ramadhan_text_length_check;
alter table public.aspirasi_ramadhan add constraint aspirasi_ramadhan_text_length_check check (
  char_length(coalesce(form_version,'')) <= 30
  and char_length(coalesce(program_dipertahankan,'')) <= 500
  and char_length(coalesce(program_dipertahankan_lainnya,'')) <= 200
  and char_length(coalesce(usulan_baru,'')) <= 500
  and char_length(coalesce(saran_lain,'')) <= 1000
  and char_length(coalesce(nama,'')) <= 100
  and char_length(coalesce(whatsapp,'')) <= 20
  and char_length(coalesce(catatan_internal,'')) <= 2000
);

create index if not exists aspirasi_ramadhan_created_at_idx on public.aspirasi_ramadhan (created_at desc);
create index if not exists aspirasi_ramadhan_status_idx on public.aspirasi_ramadhan (status, created_at desc);
create index if not exists aspirasi_ramadhan_partisipasi_idx on public.aspirasi_ramadhan (partisipasi);
create index if not exists aspirasi_ramadhan_program_prioritas_gin_idx on public.aspirasi_ramadhan using gin (program_prioritas);
create index if not exists aspirasi_ramadhan_area_peningkatan_gin_idx on public.aspirasi_ramadhan using gin (area_peningkatan);
create index if not exists aspirasi_ramadhan_program_dipertahankan_gin_idx on public.aspirasi_ramadhan using gin (program_dipertahankan_pilihan);

alter table public.aspirasi_ramadhan enable row level security;

drop policy if exists "Publik dapat mengirim aspirasi Ramadhan" on public.aspirasi_ramadhan;
create policy "Publik dapat mengirim aspirasi Ramadhan"
on public.aspirasi_ramadhan
for insert
to anon, authenticated
with check (
  status = 'baru'
  and source_channel = 'website'
  and catatan_internal is null
  and reviewed_at is null
  and reviewed_by is null
);

drop policy if exists "Admin dapat membaca aspirasi Ramadhan" on public.aspirasi_ramadhan;
create policy "Admin dapat membaca aspirasi Ramadhan"
on public.aspirasi_ramadhan
for select
to authenticated
using (true);

drop policy if exists "Admin dapat memperbarui aspirasi Ramadhan" on public.aspirasi_ramadhan;
create policy "Admin dapat memperbarui aspirasi Ramadhan"
on public.aspirasi_ramadhan
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Admin dapat menghapus aspirasi Ramadhan" on public.aspirasi_ramadhan;
create policy "Admin dapat menghapus aspirasi Ramadhan"
on public.aspirasi_ramadhan
for delete
to authenticated
using (true);

revoke all on table public.aspirasi_ramadhan from anon, authenticated;

grant insert (
  submission_token,form_version,program_prioritas,program_lainnya,area_peningkatan,
  peningkatan_lainnya,program_dipertahankan,program_dipertahankan_pilihan,
  program_dipertahankan_lainnya,usulan_baru,partisipasi,saran_lain,
  nama,whatsapp,source_channel
) on table public.aspirasi_ramadhan to anon, authenticated;

grant select, update, delete on table public.aspirasi_ramadhan to authenticated;
grant usage, select on sequence public.aspirasi_ramadhan_id_seq to anon, authenticated;

comment on table public.aspirasi_ramadhan is 'Aspirasi jamaah untuk Program SMART Ramadhan 1448 H MJHK.';
comment on column public.aspirasi_ramadhan.catatan_internal is 'Catatan tindak lanjut yang hanya dapat diakses admin terautentikasi.';

commit;
